/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import javax.swing.JLabel;
import javax.swing.JTextField;
import view.halamanLanjutanTransaksi;
import controller.DialogFormPeminjamanController;
/**
 *
 * @author User
 */
public class dialogFormPeminjaman extends javax.swing.JDialog {
    private DialogFormPeminjamanController controller;
    private halamanPeminjamanKendaraan root;
    private int id;

    
    
    public dialogFormPeminjaman(java.awt.Frame parent, boolean modal,int id) {
        super(parent, modal);
        this.root = (halamanPeminjamanKendaraan) parent;
        this.id = id;
        initComponents();
        controller = new DialogFormPeminjamanController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPeminjam = new javax.swing.JPanel();
        LabelNama = new javax.swing.JLabel();
        LabelNIK = new javax.swing.JLabel();
        LabelNoTelp = new javax.swing.JLabel();
        LabelEmail = new javax.swing.JLabel();
        tf_nama = new javax.swing.JTextField();
        tf_nik = new javax.swing.JTextField();
        tf_notelp = new javax.swing.JTextField();
        tf_email1 = new javax.swing.JTextField();
        bt_refresh = new javax.swing.JButton();
        Labelperiksa = new javax.swing.JLabel();
        BtnLanjut = new javax.swing.JButton();
        LabelAlamat = new javax.swing.JLabel();
        tf_alamatjl = new javax.swing.JTextField();
        LabelJl = new javax.swing.JLabel();
        LabelKec = new javax.swing.JLabel();
        tf_alamatkec = new javax.swing.JTextField();
        LabelKel = new javax.swing.JLabel();
        tf_alamatkel = new javax.swing.JTextField();
        tf_alamatkota = new javax.swing.JTextField();
        LabelKota = new javax.swing.JLabel();
        BtnKembali = new javax.swing.JButton();
        tf_email2 = new javax.swing.JTextField();
        LabelInfo = new javax.swing.JLabel();
        LabelJudul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelPeminjam.setBackground(new java.awt.Color(255, 255, 255));
        PanelPeminjam.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "\n\n", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        LabelNama.setText("Nama");

        LabelNIK.setText("NIK");

        LabelNoTelp.setText("No. Telp");

        LabelEmail.setText("Email");

        tf_email1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        bt_refresh.setText("Clear");
        bt_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_refreshActionPerformed(evt);
            }
        });

        Labelperiksa.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        Labelperiksa.setText("*Periksalah data dengan benar sebelum Lanjut Transaksi ");

        BtnLanjut.setText("Lanjut Transaksi");
        BtnLanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLanjutActionPerformed(evt);
            }
        });

        LabelAlamat.setText("Alamat");

        tf_alamatjl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_alamatjlActionPerformed(evt);
            }
        });

        LabelJl.setText("Jl.");

        LabelKec.setText("Kec.");

        LabelKel.setText("Kel.");

        tf_alamatkel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_alamatkelActionPerformed(evt);
            }
        });

        LabelKota.setText("Kota/Kab.");

        BtnKembali.setText("Kembali");
        BtnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKembaliActionPerformed(evt);
            }
        });

        tf_email2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tf_email2.setText("@");

        LabelInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelInfo.setText(" ");

        LabelJudul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelJudul.setText("Form Informasi Peminjam");

        javax.swing.GroupLayout PanelPeminjamLayout = new javax.swing.GroupLayout(PanelPeminjam);
        PanelPeminjam.setLayout(PanelPeminjamLayout);
        PanelPeminjamLayout.setHorizontalGroup(
            PanelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPeminjamLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PanelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Labelperiksa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelPeminjamLayout.createSequentialGroup()
                        .addComponent(BtnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnLanjut, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(PanelPeminjamLayout.createSequentialGroup()
                        .addGroup(PanelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNoTelp)
                            .addComponent(LabelEmail)
                            .addComponent(LabelNIK)
                            .addComponent(LabelNama))
                        .addGap(45, 45, 45)
                        .addGroup(PanelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPeminjamLayout.createSequentialGroup()
                                .addComponent(LabelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_refresh))
                            .addGroup(PanelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                .addComponent(tf_notelp)
                                .addComponent(tf_nik)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPeminjamLayout.createSequentialGroup()
                                    .addComponent(tf_email1)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_email2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PanelPeminjamLayout.createSequentialGroup()
                        .addComponent(LabelAlamat)
                        .addGap(65, 65, 65)
                        .addGroup(PanelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPeminjamLayout.createSequentialGroup()
                                .addComponent(LabelKec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_alamatkec, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelPeminjamLayout.createSequentialGroup()
                                .addComponent(LabelKota)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_alamatkota, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelPeminjamLayout.createSequentialGroup()
                                .addComponent(LabelKel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_alamatkel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelPeminjamLayout.createSequentialGroup()
                                .addComponent(LabelJl)
                                .addGap(27, 27, 27)
                                .addComponent(tf_alamatjl, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPeminjamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelPeminjamLayout.setVerticalGroup(
            PanelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPeminjamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_refresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNIK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_notelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNoTelp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_email2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_email1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_alamatjl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelJl)
                    .addComponent(LabelAlamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_alamatkel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelKel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_alamatkec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelKec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_alamatkota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelKota))
                .addGap(18, 18, 18)
                .addComponent(LabelInfo)
                .addGap(13, 13, 13)
                .addComponent(Labelperiksa)
                .addGap(18, 18, 18)
                .addGroup(PanelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLanjut)
                    .addComponent(BtnKembali))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPeminjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_refreshActionPerformed
//        clear();
//        tf_nama.requestFocus();
    }//GEN-LAST:event_bt_refreshActionPerformed

    private void BtnLanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLanjutActionPerformed
//        if (tf_nik.getText().isEmpty()
//            || tf_nama.getText().isEmpty()
//            || tf_alamatjl.getText().isEmpty()
//            || tf_alamatkel.getText().isEmpty()
//            || tf_alamatkec.getText().isEmpty()
//            || tf_alamatkota.getText().isEmpty()
//            || tf_notelp.getText().isEmpty ()
//            || tf_email1.getText().isEmpty()
//            || tf_email2.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Data Pengisian Belum Benar");
//        } else {
//            String nama     = tf_nama.getText();
//            String nik      = tf_nik.getText();
//            String alamat   = "Jl. " +tf_alamatjl.getText() +", Kel. "
//            +tf_alamatkel.getText() +", Kec. "
//            +tf_alamatkec.getText() +", "
//            +tf_alamatkota.getText();
//            String tlp      = tf_notelp.getText();
//            String email    = tf_email1.getText()+tf_email2.getText();
//
//            ShowNama.setText(nama);
//            ShowNIK.setText(nik);
//            ShowAlamat.setText(alamat);
//            ShowNoTelp.setText(tlp);
//            ShowEmail.setText(email);
//
//            this.setVisible(false);
//            menu_transaksi rm = new menu_transaksi();
//            rm.setVisible(true);
//
//        }
//        halamanLanjutanTransaksi hl = new halamanLanjutanTransaksi();
//        hl.setVisible(true);
//        
        // get parent frame
        if (controller.transaksi()) {
            this.root.dispose();
        }
    }//GEN-LAST:event_BtnLanjutActionPerformed

    private void tf_alamatjlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_alamatjlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_alamatjlActionPerformed

    private void tf_alamatkelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_alamatkelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_alamatkelActionPerformed

    private void BtnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnKembaliActionPerformed

    public JTextField getTf_alamatjl() {
        return tf_alamatjl;
    }

    public JTextField getTf_alamatkec() {
        return tf_alamatkec;
    }

    public JTextField getTf_alamatkel() {
        return tf_alamatkel;
    }

    public JTextField getTf_alamatkota() {
        return tf_alamatkota;
    }

    public JTextField getTf_email1() {
        return tf_email1;
    }

    public JTextField getTf_email2() {
        return tf_email2;
    }

    public JTextField getTf_nama() {
        return tf_nama;
    }

    public JTextField getTf_nik() {
        return tf_nik;
    }

    public JTextField getTf_notelp() {
        return tf_notelp;
    }

    public JLabel getLabelInfo() {
        return LabelInfo;
    }

    public int getId() {
        return id;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnKembali;
    private javax.swing.JButton BtnLanjut;
    private javax.swing.JLabel LabelAlamat;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelInfo;
    private javax.swing.JLabel LabelJl;
    private javax.swing.JLabel LabelJudul;
    private javax.swing.JLabel LabelKec;
    private javax.swing.JLabel LabelKel;
    private javax.swing.JLabel LabelKota;
    private javax.swing.JLabel LabelNIK;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelNoTelp;
    private javax.swing.JLabel Labelperiksa;
    private javax.swing.JPanel PanelPeminjam;
    private javax.swing.JButton bt_refresh;
    private javax.swing.JTextField tf_alamatjl;
    private javax.swing.JTextField tf_alamatkec;
    private javax.swing.JTextField tf_alamatkel;
    private javax.swing.JTextField tf_alamatkota;
    private javax.swing.JTextField tf_email1;
    private javax.swing.JTextField tf_email2;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_nik;
    private javax.swing.JTextField tf_notelp;
    // End of variables declaration//GEN-END:variables
}
